### ISSUE TITLE
bug when trying to lapply summary on a psem containing GLMs

### ISSUE THREAD

**Issue by Canderson156** [jslefche/piecewiseSEM#254] opened 2022-04-20 18:09 UTC
Hi there,

I came across an error or bug in a piece of code that works fine when all models in a psem are lm models, but throws an error when a glm is included. I'm not sure if the issue comes from piecewiseSEM, lapply, or if I could specify this differently to avoid the error.

**This works fine:**

library(semEff)
data(keeley, package = "piecewiseSEM")
keeley <- as_tibble(keeley)
keeley$presence <- sample(c(0,1), replace = TRUE, size = nrow(keeley))
keeley$species <- sample(c("cat","dog"), replace = TRUE, size = nrow(keeley))
keeley.split <- group_split(keeley, species)

#path model structure
path.structure.lm <- function(x) {
  
  path <- psem(
    lm(age ~ distance, data = x),
    lm(hetero ~ distance, data = x),
    lm(abiotic ~ distance, data = x),
    lm(firesev ~ age, data = x),
    lm(cover ~ firesev, data = x),
    lm(rich ~ distance + hetero + abiotic + cover, data = x)
  ) 
}

#apply the path model structure to each species
keeley.models.lm <- lapply(keeley.split, path.structure.lm)

#get the summary of the path model for each species
psem_summary <- lapply(keeley.models.lm, summary)

**The same code with a glm has the following error:**

#path model structure
path.structure.glm <- function(x) {
  
  path <- psem(
    lm(age ~ distance, data = x),
    lm(hetero ~ distance, data = x),
    lm(abiotic ~ distance, data = x),
    lm(firesev ~ age, data = x),
    lm(cover ~ firesev, data = x),
    lm(rich ~ distance + hetero + abiotic + cover, data = x),
    glm(presence ~ rich + cover + distance, data = x, family = binomial)
  ) 
}

#apply the path model structure to each species
keeley.models.glm <- lapply(keeley.split, path.structure.glm)

#get the summary of the path model for each species
psem_summary <- lapply(keeley.models.glm, summary)

>Error in is.data.frame(data) : object 'x' not found

I found this error in my own code, and it occurs with this reproducible data as well, so I'm guessing the issue occurs when including glms

**Comment by Canderson156** [comment] 2022-05-26 15:38
Hi, wondering if you might have a chance to think about this issue any time soon?

**Comment by jslefche** [comment] 2022-06-23 16:29
@Canderson156 I cannot reproduce using version 2.2.0. Please update to the latest development version using `devtools::install_github("jslefche/piecewiseSEM@devel")` and see if that fixes. Closing but reopen if it does not fix

**Closed by jslefche** 2022-06-23 16:29 UTC

**Comment by Canderson156** [comment] 2022-06-27 17:19
Updating to the development version did fix the issue. Thanks!
