### ISSUE TITLE
Error in cbind(ret, isSig(ret[, 5])) : object 'ret' not found

### ISSUE THREAD

**Issue by liaojiahui-r** [jslefche/piecewiseSEM#238] opened 2021-07-27 12:15 UTC
Could it be a issue with R version > 4.0?

`
12	cbind(ret, isSig(ret[, 5]))
11	getCoefficients(i, data, test.statistic, test.type)
10	FUN(X[[i]], ...)
9	lapply(modelList, function(i) { if (all(class(i) %in% c("formula.cerror"))) { ret <- cerror(i, modelList, data) names(ret) <- c("Response", "Predictor", "Estimate", ...
8	do.call(rbind, lapply(modelList, function(i) { if (all(class(i) %in% c("formula.cerror"))) { ret <- cerror(i, modelList, data) names(ret) <- c("Response", "Predictor", "Estimate", ...
7	unstdCoefs(bNewMod, data)
6	testBasisSetElements(i, b, modelList, data, conditioning, .progressBar, pb)
5	FUN(X[[i]], ...)
4	lapply(1:length(b), function(i) testBasisSetElements(i, b, modelList, data, conditioning, .progressBar, pb))
3	do.call(rbind, lapply(1:length(b), function(i) testBasisSetElements(i, b, modelList, data, conditioning, .progressBar, pb)))
2	dSep(dTable, basis.set, direction, conserve, conditional, .progressBar)
1	fisherC(ew.psem, .progressBar = FALSE)
`

`─ Session info ──────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       macOS Big Sur 10.16         
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Asia/Shanghai               
 date     2021-07-27                  

─ Packages ──────────────────────────────────────────────────
 ! package      * version    date       lib
   abind          1.4-5      2016-07-21 [1]
   assertthat     0.2.1      2019-03-21 [1]
   backports      1.2.1      2020-12-09 [1]
   boot           1.3-25     2020-04-26 [2]
   broom          0.7.3      2020-12-16 [1]
   callr          3.5.1      2020-10-13 [1]
   car            3.0-10     2020-09-29 [1]
   carData        3.0-4      2020-05-22 [1]
   cellranger     1.1.0      2016-07-27 [1]
   cli            2.2.0      2020-11-20 [1]
   coda           0.19-4     2020-09-30 [1]
   codetools      0.2-18     2020-11-04 [2]
   colorspace     2.0-0      2020-11-11 [1]
   crayon         1.3.4      2017-09-16 [1]
   curl           4.3        2019-12-02 [1]
   data.table     1.13.6     2020-12-30 [1]
   DBI            1.1.1      2021-01-15 [1]
   dbplyr         2.0.0      2020-11-03 [1]
   desc           1.2.0      2018-05-01 [1]
   devtools     * 2.3.2      2020-09-18 [1]
   DiagrammeR     1.0.6.1    2020-05-08 [1]
   digest         0.6.27     2020-10-24 [1]
   dplyr        * 1.0.3      2021-01-15 [1]
   ellipsis       0.3.1      2020-05-15 [1]
   emmeans        1.5.3      2020-12-09 [1]
   estimability   1.3        2018-02-11 [1]
   evaluate       0.14       2019-05-28 [1]
   fansi          0.4.2      2021-01-15 [1]
   farver         2.0.3      2020-01-16 [1]
   forcats      * 0.5.0      2020-03-01 [1]
   foreign        0.8-81     2020-12-22 [2]
   fs             1.5.0      2020-07-31 [1]
   generics       0.1.0      2020-10-31 [1]
   ggcorrplot     0.1.3      2019-05-19 [1]
   ggforce        0.3.2      2020-06-23 [1]
   ggplot2      * 3.3.3      2020-12-30 [1]
   ggraph       * 2.0.4      2020-11-16 [1]
   ggrepel        0.9.1      2021-01-15 [1]
   ggsci          2.9        2018-05-14 [1]
   glue           1.4.2      2020-08-27 [1]
   graphlayouts   0.7.1      2020-10-26 [1]
   gridExtra      2.3        2017-09-09 [1]
   gtable         0.3.0      2019-03-25 [1]
   haven          2.3.1      2020-06-01 [1]
   hms            1.0.0      2021-01-13 [1]
   htmltools      0.5.1      2021-01-12 [1]
   htmlwidgets    1.5.3      2020-12-10 [1]
   httr           1.4.2      2020-07-20 [1]
   igraph       * 1.2.6      2020-10-06 [1]
   jsonlite       1.7.2      2020-12-09 [1]
   knitr          1.30       2020-09-22 [1]
   labeling       0.4.2      2020-10-20 [1]
   lattice        0.20-41    2020-04-02 [2]
   lavaan       * 0.6-7      2020-07-31 [1]
   lifecycle      0.2.0      2020-03-06 [1]
   lme4         * 1.1-26     2020-12-01 [1]
   lmerTest     * 3.1-3      2020-10-23 [1]
   lubridate      1.7.9.2    2020-11-13 [1]
   magrittr       2.0.1      2020-11-17 [1]
   MASS           7.3-53     2020-09-09 [1]
   Matrix       * 1.3-2      2021-01-06 [2]
   memoise        1.1.0      2017-04-21 [1]
   mgcv           1.8-33     2020-08-27 [2]
   minqa          1.2.4      2014-10-09 [1]
   mnormt         2.0.2      2020-09-01 [1]
   modelr         0.1.8      2020-05-19 [1]
   multcomp       1.4-15     2020-11-14 [1]
   munsell        0.5.0      2018-06-12 [1]
   mvtnorm        1.1-1      2020-06-09 [1]
   nlme           3.1-151    2020-12-10 [1]
   nloptr         1.2.2.2    2020-07-02 [1]
   numDeriv       2016.8-1.1 2019-06-06 [1]
   openxlsx       4.2.3      2020-10-27 [1]
   pbivnorm       0.6.0      2015-01-23 [1]
 V piecewiseSEM * 2.1.2      2021-07-27 [1]
   pillar         1.4.7      2020-11-20 [1]
   pkgbuild       1.2.0      2020-12-15 [1]
   pkgconfig      2.0.3      2019-09-22 [1]
   pkgload        1.1.0      2020-05-29 [1]
   plyr           1.8.6      2020-03-03 [1]
   polyclip       1.10-0     2019-03-14 [1]
   prettyunits    1.1.1      2020-01-24 [1]
   processx       3.4.5      2020-11-30 [1]
   ps             1.5.0      2020-12-05 [1]
   purrr        * 0.3.4      2020-04-17 [1]
   R6             2.5.0      2020-10-28 [1]
   RColorBrewer   1.1-2      2014-12-07 [1]
   Rcpp           1.0.6      2021-01-15 [1]
   readr        * 1.4.0      2020-10-05 [1]
   readxl       * 1.3.1      2019-03-13 [1]
   remotes        2.4.0      2021-06-02 [1]
   reprex         0.3.0      2019-05-16 [1]
   reshape2       1.4.4      2020-04-09 [1]
   rio            0.5.16     2018-11-26 [1]
   rlang          0.4.10     2020-12-30 [1]
   rmarkdown      2.6        2020-12-14 [1]
   rprojroot      2.0.2      2020-11-15 [1]
   rstudioapi     0.13       2020-11-12 [1]
   rvest          0.3.6      2020-07-25 [1]
   sandwich       3.0-0      2020-10-02 [1]
   scales         1.1.1      2020-05-11 [1]
   sessioninfo    1.1.1      2018-11-05 [1]
   statmod        1.4.35     2020-10-19 [1]
   stringi        1.5.3      2020-09-09 [1]
   stringr      * 1.4.0      2019-02-10 [1]
   survival       3.2-7      2020-09-28 [2]
   testthat       3.0.1      2020-12-17 [1]
   TH.data        1.0-10     2019-01-21 [1]
   tibble       * 3.0.5      2021-01-15 [1]
   tidygraph    * 1.2.0      2020-05-12 [1]
   tidyr        * 1.1.2      2020-08-27 [1]
   tidyselect     1.1.0      2020-05-11 [1]
   tidyverse    * 1.3.0      2019-11-21 [1]
   tinytex        0.28       2020-12-14 [1]
   tmvnsim        1.0-2      2016-12-15 [1]
   tweenr         1.0.1      2018-12-14 [1]
   usethis      * 2.0.0      2020-12-10 [1]
   vctrs          0.3.6      2020-12-17 [1]
   viridis        0.5.1      2018-03-29 [1]
   viridisLite    0.3.0      2018-02-01 [1]
   visNetwork     2.0.9      2019-12-06 [1]
   withr          2.4.0      2021-01-16 [1]
   xfun           0.20       2021-01-06 [1]
   xml2           1.3.2      2020-04-23 [1]
   xtable         1.8-4      2019-04-21 [1]
   yaml           2.2.1      2020-02-01 [1]
   zip            2.1.1      2020-08-27 [1]
   zoo            1.8-8      2020-05-02 [1]
 source                                
 CRAN (R 4.0.2)                        
...             
                   

[1] /Users/xxx
[2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

 V ── Loaded and on-disk version mismatch.`

**Comment by LdiaWong** [comment] 2022-03-04 16:54
I get this error too...

**Comment by fidlerdb** [comment] 2022-03-07 13:13
And me! No idea why yet...

**Comment by LdiaWong** [comment] 2022-03-07 15:38
So I noticed one thing that has helped with this (doesn't work all the time, but does sometimes!): I often have the package "lmerTest" loaded in my library. I recall reading somewhere that the piecewiseSEM package doesn't do well with lmerTest, so I tried unloading the package before running the SEM (detach("package:lmerTest", unload=TRUE) and it sometimes works!

**Comment by fidlerdb** [comment] 2022-03-08 11:20
Thanks LdiaWong, that may have been the issue for me. For info, I swapped to the development version (on 2022-03-07) and it now seems to work fine, even with lmerTest loaded :)

**Comment by MatsVanGestel** [comment] 2022-03-24 14:28
>I swapped to the development version (on 2022-03-07) and it now seems to work fine, even with lmerTest loaded :)

Hi! I'm having this issue as well and was wondering how you switch to the developmet version? This refers to the development version of R(Studio) or the package itself? 

Thanks in advance!

**Comment by jslefche** [comment] 2022-03-24 14:31
***@***.***”)`

😊

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by LdiaWong** [comment] 2022-03-24 18:42
> > I swapped to the development version (on 2022-03-07) and it now seems to work fine, even with lmerTest loaded :)
> 
> Hi! I'm having this issue as well and was wondering how you switch to the developmet version? This refers to the development version of R(Studio) or the package itself?
> 
> Thanks in advance!

I think maybe @fidlerdb was talking about the newest version of R? (it was still in development when that comment was written but it's been released since then: https://www.r-project.org/) --correct me if I am wrong about this though!

That said, I tried updating my R version just now, and the SEM still doesn't run if lmerTest is loaded. It _did_ run successfully when I manually detached lmerTest...
`detach("package:lmerTest", unload=TRUE)` 
Maybe that helps?

**Comment by MatsVanGestel** [comment] 2022-03-25 09:21
Thank you both for your answers! I am, however, still not getting any results... I was able to run library(devtools) and instal_github(...), but am still getting the same error message. I've also trier re-launching R a couple of times and unloading lmerTest 

I'm just using summary(MyModel, .progressBar = F).

**Comment by jslefche** [comment] 2022-03-25 13:20
Folks, I've gotten a few inquiries about this. Alas, I can't seem to reproduce. It does not seem to come down to `lmerTest`, eg:

```
library(piecewiseSEM)
library(lmerTest)

data <- data.frame(
  y = rnorm(50, 100),
  x = rnorm(50, 100),
  random = letters[1:5])

model <- psem(
  lmer(y ~ x + (1 | random), data)
  )

summary(model)  
```

The new version of the package does not use `lmerTest` to obtain P-values for the d-sep test, so it shouldn't generate any conflicts.

Can someone send a reproducible example?

**Comment by LdiaWong** [comment] 2022-03-25 19:18
Okay here's a bit of my data... I'm sorry it's a little messy!

`library(lme4) 
#library(lmerTest) trying running without lmerTest loaded first
library(piecewiseSEM)

year <- as.character(c(2013,2013,2013,2013, 2013, 2014, 2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015,2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017, 2018, 2018, 2018, 2018, 2018, 2018,2019, 2019, 2019, 2019, 2019, 2021, 2021, 2021, 2021, 2021, 2021))
site <- c('BC','FT','MC','RP','VB','BC','FT','KC','KP','MC','RP','BC','FT','KC','KP','MC','RP','BC','FT','KC','KP','RP','VB','BC','FT','KC','KP','RP','BC','FT','KC','KP','RP','VB','BC','FT','KC','KP','RP','BC','FT','KC','KP','RP','VB')
totCells <- as.numeric(c(2.69,2.41,2.47,2.51,1.80,2.90,2.63,3.12,2.01,2.92,3.34,2.35,1.89,3.61,2.19,2.15,2.50,1.70,2.69,3.11,2.09,1.63,1.19,2.58,2.58,3.20,2.42,3.45,2.47,3.06,2.7,2.99,3.04,1.19,3.76,2.64,3.28,2.00,2.38,2.18,2.06,2.30,2.12,2.71,1.64))
totIndv <- as.numeric(c(2,3,2,5,1,5,8,14,8,10,8,3,3,18,8,4,8,2,6,6,5,1,1,3,4,11,5,13,3,13,11,18,5,2,10,8,13,5,12,8,5,7,4,6,1))
bee_temp <- as.numeric(c(12.97,12.26,12.89,12.61,9.04,11.99,11.45,11.12,11.44,12.25,11.86,11.78,10.89,10.90,11.14,11.71,11.53,12.03,12.00,11.24,10.81,12.04,8.37,12.83,12.98,11.82,11.42,12.24,14.34,14.28,13.69,13.61,13.42,10.09,12.62,11.32,11.20,9.80,11.56,13.81,12.33,12.42,12.55,12.62,9.18))
bee_precip <- as.numeric(c(183.77,240.18,179.29,201.45,248.29,165.56,290.41,209.47,217.78,166.14,211.60,280.59,431.98,328.00,342.95,279.39,333.30,216.59,246.03,232.37,236.81,225.86,251.92,140.17,165.89,157.27,161.57,149.98,105.06,117.09,119.21,115.45,108.61,118.55,166.30,234.45,221.73,230.21,196.00,197.00,256.09,238.26,248.91,219.72,263.02))
logFlowers <- as.numeric(c(1.53,2.19,1.65,0.79,1.10,2.25,0.94,0.56,1.28,1.53,0.83,2.04,1.16,1.46,0.78,0.47,0.74,2.78,1.88,3.31,1.09,0.74,0.90,2.43,1.68,2.19,0.76,1.46,0.27,1.05,1.10,0.94,0.29,0.90,1.88,1.41,1.24,0.68,0.71,0.67,1.46,1.51,1.09,0.40,1.16))
totCellsPrev <- as.numeric(c(NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,2.69,2.41,NA,NA,2.47,2.51,2.90,2.63,3.12,2.01,3.34,0.00,2.35,1.89,3.61,2.19,2.50,1.70,2.69,3.11,2.09,1.63,1.19,2.58,2.58,3.20,2.42,3.45,3.76,2.64,3.28,2.00,2.38,0.00))
flr_temp <- as.numeric(c(2.74,2.10,3.08,1.94,0.71,2.19,1.41,1.71,3.22,2.34,1.67,2.66,2.39,2.16,2.04,3.22,2.93,3.37,1.61,1.73,2.87,2.31,0.98,3.96,3.31,2.92,3.16,2.51,4.66,3.94,3.04,3.72,3.11,1.14,1.74,1.08,1.06,2.11,0.62,3.64,2.51,2.05,4.14,2.24,1.08))
flr_precip <- as.numeric(c(441.25,731.49,434.96,540.43,804.68,514.37,1002.72,726.53,755.44,519.08,679.43,556.48,872.90,707.11,728.07,551.51,667.53,518.39,737.46,654.02,675.56,595.49,798.91,622.97,959.16,782.10,807.41,727.60,380.87,604.73,507.04,520.29,459.57,661.48,675.94,1049.71,871.37,895.37,822.50,430.48,664.97,565.32,586.65,510.73,730.31))

dat <- data.frame(year, site, totCells, totIndv, bee_temp, bee_precip, logFlowers, totCellsPrev, flr_temp, flr_precip, stringsAsFactors = FALSE)


modCells <- lm(totCells ~ totIndv + bee_temp + bee_precip + logFlowers, data = dat)
modIndv <- glmer(totIndv ~ totCellsPrev + (1|year), family = "poisson", data = dat)
modFls <- lmer(logFlowers ~ flr_temp + flr_precip + (1|site) + (1|year), data = dat)

pSEMdat <- psem(modCells, modIndv, modFls,
                flr_temp %~~% bee_temp,
                flr_temp %~~% bee_precip,
                flr_precip %~~% bee_precip,
                flr_precip %~~% bee_temp,
                flr_temp %~~% flr_precip,
                bee_temp %~~% bee_precip
)

mod1Sum <- (summary(pSEMdat, conserve = T, .progressBar = FALSE))
mod1Sum

#now re-run with lmerTest loaded
library(lmerTest)`

**Comment by LdiaWong** [comment] 2022-03-25 19:21
Okay here's a bit of my data... I'm sorry it's a little messy!

```
library(lme4) 
#library(lmerTest) trying running without lmerTest loaded first
library(piecewiseSEM)

year <- as.character(c(2013,2013,2013,2013, 2013, 2014, 2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015,2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017, 2018, 2018, 2018, 2018, 2018, 2018,2019, 2019, 2019, 2019, 2019, 2021, 2021, 2021, 2021, 2021, 2021))
site <- c('BC','FT','MC','RP','VB','BC','FT','KC','KP','MC','RP','BC','FT','KC','KP','MC','RP','BC','FT','KC','KP','RP','VB','BC','FT','KC','KP','RP','BC','FT','KC','KP','RP','VB','BC','FT','KC','KP','RP','BC','FT','KC','KP','RP','VB')
totCells <- as.numeric(c(2.69,2.41,2.47,2.51,1.80,2.90,2.63,3.12,2.01,2.92,3.34,2.35,1.89,3.61,2.19,2.15,2.50,1.70,2.69,3.11,2.09,1.63,1.19,2.58,2.58,3.20,2.42,3.45,2.47,3.06,2.7,2.99,3.04,1.19,3.76,2.64,3.28,2.00,2.38,2.18,2.06,2.30,2.12,2.71,1.64))
totIndv <- as.numeric(c(2,3,2,5,1,5,8,14,8,10,8,3,3,18,8,4,8,2,6,6,5,1,1,3,4,11,5,13,3,13,11,18,5,2,10,8,13,5,12,8,5,7,4,6,1))
bee_temp <- as.numeric(c(12.97,12.26,12.89,12.61,9.04,11.99,11.45,11.12,11.44,12.25,11.86,11.78,10.89,10.90,11.14,11.71,11.53,12.03,12.00,11.24,10.81,12.04,8.37,12.83,12.98,11.82,11.42,12.24,14.34,14.28,13.69,13.61,13.42,10.09,12.62,11.32,11.20,9.80,11.56,13.81,12.33,12.42,12.55,12.62,9.18))
bee_precip <- as.numeric(c(183.77,240.18,179.29,201.45,248.29,165.56,290.41,209.47,217.78,166.14,211.60,280.59,431.98,328.00,342.95,279.39,333.30,216.59,246.03,232.37,236.81,225.86,251.92,140.17,165.89,157.27,161.57,149.98,105.06,117.09,119.21,115.45,108.61,118.55,166.30,234.45,221.73,230.21,196.00,197.00,256.09,238.26,248.91,219.72,263.02))
logFlowers <- as.numeric(c(1.53,2.19,1.65,0.79,1.10,2.25,0.94,0.56,1.28,1.53,0.83,2.04,1.16,1.46,0.78,0.47,0.74,2.78,1.88,3.31,1.09,0.74,0.90,2.43,1.68,2.19,0.76,1.46,0.27,1.05,1.10,0.94,0.29,0.90,1.88,1.41,1.24,0.68,0.71,0.67,1.46,1.51,1.09,0.40,1.16))
totCellsPrev <- as.numeric(c(NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,2.69,2.41,NA,NA,2.47,2.51,2.90,2.63,3.12,2.01,3.34,0.00,2.35,1.89,3.61,2.19,2.50,1.70,2.69,3.11,2.09,1.63,1.19,2.58,2.58,3.20,2.42,3.45,3.76,2.64,3.28,2.00,2.38,0.00))
flr_temp <- as.numeric(c(2.74,2.10,3.08,1.94,0.71,2.19,1.41,1.71,3.22,2.34,1.67,2.66,2.39,2.16,2.04,3.22,2.93,3.37,1.61,1.73,2.87,2.31,0.98,3.96,3.31,2.92,3.16,2.51,4.66,3.94,3.04,3.72,3.11,1.14,1.74,1.08,1.06,2.11,0.62,3.64,2.51,2.05,4.14,2.24,1.08))
flr_precip <- as.numeric(c(441.25,731.49,434.96,540.43,804.68,514.37,1002.72,726.53,755.44,519.08,679.43,556.48,872.90,707.11,728.07,551.51,667.53,518.39,737.46,654.02,675.56,595.49,798.91,622.97,959.16,782.10,807.41,727.60,380.87,604.73,507.04,520.29,459.57,661.48,675.94,1049.71,871.37,895.37,822.50,430.48,664.97,565.32,586.65,510.73,730.31))

dat <- data.frame(year, site, totCells, totIndv, bee_temp, bee_precip, logFlowers, totCellsPrev, flr_temp, flr_precip, stringsAsFactors = FALSE)


modCells <- lm(totCells ~ totIndv + bee_temp + bee_precip + logFlowers, data = dat)
modIndv <- glmer(totIndv ~ totCellsPrev + (1|year), family = "poisson", data = dat)
modFls <- lmer(logFlowers ~ flr_temp + flr_precip + (1|site) + (1|year), data = dat)

pSEMdat <- psem(modCells, modIndv, modFls,
                flr_temp %~~% bee_temp,
                flr_temp %~~% bee_precip,
                flr_precip %~~% bee_precip,
                flr_precip %~~% bee_temp,
                flr_temp %~~% flr_precip,
                bee_temp %~~% bee_precip
)

mod1Sum <- (summary(pSEMdat, conserve = T, .progressBar = FALSE))
mod1Sum

#now re-run with lmerTest loaded
library(lmerTest)
```

**Comment by jslefche** [comment] 2022-03-28 13:52
Thanks @LdiaWong 

I can't seem to reproduce, your code runs fine for me. Are you running version 2.2.0 of the package? What version of R are you running?

**Comment by MatsVanGestel** [comment] 2022-03-29 10:18
> 

Thank you for the link! Unfortunately, I constantly get the error message "could not find function "install.packages"", even after re-installing R and RStudio. Does anyone have experience with this issue? 

Thanks!

**Comment by LdiaWong** [comment] 2022-04-06 18:41
@jslefche oh hmmm... I have a very recent version of R and RStudio (4.1.3), but only version 2.1.0 of the piecewiseSEM package. I tried uninstalling the package and re-installing it to see if it would update, but I still get 2.1.0. Is there somewhere I can download the newer version? Thanks in advance! I looked at your github page for the package but didn't find 2.2.0 I think?

**Comment by jslefche** [comment] 2022-04-06 20:31
If you run this code ***@***.***”)` it should install version 2.2.0 with last updated date of March 2022

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by LdiaWong** [comment] 2022-04-07 00:38
I sorry (this feels silly to ask...), but what is meant by ***@***.***”)`? Is it a link to something?

**Comment by MatsVanGestel** [comment] 2022-06-03 12:02
Hi all,

Has anyone made some progress with this yet? Even with simpler models, the issue is quite persistent. 

Kind regards!

**Comment by LdiaWong** [comment] 2022-06-04 22:33
Hmm... no I haven't... :(

**Comment by jslefche** [comment] 2022-06-23 18:44
In lack of reproducible example, closing for now

**Closed by jslefche** 2022-06-23 18:44 UTC

**Comment by jslefche** [comment] 2022-10-11 07:45
That specifies the branch to download, aka “devel” or development

Copy/paste the code inside the tick marks aka `` and you should be good to go

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
