### ISSUE TITLE
sem.coefs still eating a coefficient

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#63] opened 2016-07-25 13:28 UTC
Here's a result from a recent lme model

```

> mod <- lme(belowbiomass_g ~ rd + belowgallic_uM + belowCN  + 
+                                  observed_otus + Metabolism + status, 
+                                random =~ 1|Genotype, data=exp_data_func, method="ML")
> 
> 
> sem.coefs(list(mod), data=exp_data_func, standardize="scale", intercept=T)
        response      predictor    estimate  std.error p.value 
1 belowbiomass_g statusinvasive  1.14471438 0.58369983  0.0735 
2 belowbiomass_g    (Intercept) -0.85032034 0.50436733  0.0976 
3 belowbiomass_g        belowCN  0.17250292 0.10411949  0.1034 
4 belowbiomass_g             rd -0.14625998 0.15309831  0.3437 
5 belowbiomass_g  observed_otus -0.08072650 0.10845045  0.4599 
6 belowbiomass_g belowgallic_uM -0.04838411 0.09971926  0.6295 
7 belowbiomass_g     Metabolism  0.07119152 0.19163309  0.7117 


> sem.coefs(list(mod), data=exp_data_func)
        response      predictor      estimate    std.error p.value 
1 belowbiomass_g statusinvasive  1.108997e+00 5.654870e-01  0.0735 
2 belowbiomass_g        belowCN  9.408667e-03 5.678893e-03  0.1034 
3 belowbiomass_g             rd -2.834115e+00 2.966623e+00  0.3437 
4 belowbiomass_g  observed_otus -2.205835e-04 2.963386e-04  0.4599 
5 belowbiomass_g belowgallic_uM -2.111000e-04 4.350753e-04  0.6295 
6 belowbiomass_g   statusnative  2.311411e-01 5.725650e-01  0.6935 
7 belowbiomass_g     Metabolism  1.376371e-06 3.704910e-06  0.7117 
> 
```

Status is the categorical variable. There are three levels - native, invasive, and introduced.

Notice that in the intercept=T version, I also see `statusinvasive` and `(Intercept)`. I do not see `statusnative`.

 In the no intercept version, I don't see the intercept (natch), but do see `statusinvasive` and `statusnative`.

Something is getting eaten still even when `intercept=T`.

**Comment by jebyrnes** [comment] 2016-07-25 13:28
Maybe it's just a categorical variable thing?

**Comment by jebyrnes** [comment] 2016-07-25 13:30
Repeatable example - it is groups that are the problem. N.B. I'm using 1.1.4 (or, whatever devtools just downloaded from github)

```

set.seed(2016)
adf <- data.frame(grp = factor(rep(letters[1:3], 10)), y=rnorm(30))

mod <- lm(y~grp, data=adf)
sem.coefs(list(mod), data=adf)
sem.coefs(list(mod), data=adf, intercept=T)

```

**Comment by jebyrnes** [comment] 2016-07-25 13:32
Related question - with categorical variables, and scale="standardized" - are you getting accurate standardized coefs for the categorical variables, or do you need to do a +0?

**Comment by jslefche** [comment] 2016-07-27 14:38
Dunno why my comments didn't post but yes, can reproduce, and yes, will look into this

**Comment by jebyrnes** [comment] 2016-07-27 14:39
Perfeto! Been in the field with Alsterberg (who I need to get on github) so haven't had time to dig myself. Likely something simple... But the world of categorical variables and SEM - man, unexplored territory for me (and I think a lot of folk...in a non-multigroup context)

**Comment by jebyrnes** [comment] 2016-08-02 18:28
I think this will do the trick in line 17 of sem.coefs.R unless `coef` returns odd outputs of bad length for a model type - might need to get more specific for a few?

```
   #old
   # if(intercept == TRUE) irow = 1:(length(colnames(attr(terms(i), "factors"))) + 1) else irow = -1
   #replace with
    if(intercept == TRUE) irow = 1:(length(coef(i))) else irow = -1
```

**Comment by jebyrnes** [comment] 2016-08-02 18:48
FYI, this now borks if `standardize="scale"`

```
 Error in apply(newdata[, vars.to.scale], 2, function(x) { : 
  dim(X) must have a positive length 
```

**Comment by jebyrnes** [comment] 2016-08-02 19:02
Which I think is because how do you standardize a categorical variable.... FYI, this was helpful - https://www.quora.com/How-bad-is-it-to-standardize-dummy-variables

So one can standardize on the dummy 0/1 for each, but that's going to be a wee bit more coding, I think. Hrm.

**Comment by jslefche** [comment] 2016-08-03 15:01
Ok fixed the issue with categorical variables when ` intercept = T ` . Now onto your second question...

**Comment by jslefche** [comment] 2016-08-03 15:12
Yeah, not sure how to deal with this. As your post brings up, what is a standardized categorical variable?? This gets tricky when you move beyond binary variables, as in your example. I wrote some code to simply convert to an ordinal variable but not entirely comfortable with that. I'm open to suggestions...

**Comment by jebyrnes** [comment] 2016-08-08 16:31
More and more, I think with categorical variables you have to go with Relevant Range scaling. You could throw an error if range is not used? Or at least a warning for scale?

However, still seeing the 
```
 Error in apply(newdata[, vars.to.scale], 2, function(x) { : 
  dim(X) must have a positive length 
```

error when using standardize="range" using the toy example above...

**Comment by jslefche** [comment] 2017-03-10 15:04
Closing this for now since it will be completely redone for 2.0

**Closed by jslefche** 2017-03-10 15:04 UTC
