### ISSUE TITLE
Not getting the fisher.c and aic results

### ISSUE THREAD

**Issue by frva-umea** [jslefche/piecewiseSEM#58] opened 2016-06-17 09:27 UTC
Hi, I have run piecewiseSEM with the same model and it was working perfectly, but suddenly it stopped to work properly. I am getting this error:

**Error in modelList[[which(sapply(modelList, function(j) { : 
  attempt to select less than one element in get1index**

I know it has to do with my dummy variable 'Temp' (which is either 0 or 1), because when I removed it I got the  stats running properly. I know I have a direct loop, but even with the loop the package was working. It just told me that I had directed cycles!

Any idea what can be the case?

Here is part of my model:
exef_pSEM_randomList = list(  pelgpp = lm(pelgpp ~ Temp + srp, data = bent_gpp),
                                               bentgpp1 = lm(bentgpp1 ~ Temp + kd, data = bent_gpp),  
                                               srp = lm(srp ~ cDOM + bentgpp1, data = bent_gpp)
                                                  )
sem.fit(exef_pSEM_randomList, bent_gpp)

##After this part I get the error mentioned above!

Hope you can help!

**Comment by jslefche** [comment] 2016-06-17 13:35
Yes, this is a new issue that should be fixed in the latest (development) version, 1.1.3, last updated yesterday. With this version, I can't reproduce your issue:

`library(devtools)
install_githun("jslefche/piecewiseSEM")

library(piecewiseSEM)

bent_gpp = data.frame(
  pelgpp = rnorm(50),
  Temp = sample(0:1, 50, replace = T),
  srp = rnorm(50),
  bentgpp1 = rnorm(50), 
  kd = rnorm(50),
  srp = rnorm(50),
  cDOM = rnorm(50)
)


exef_pSEM_randomList = list( pelgpp = lm(pelgpp ~ Temp + srp, data = bent_gpp),
                             bentgpp1 = lm(bentgpp1 ~ Temp + kd, data = bent_gpp),
                             
                             srp = lm(srp ~ cDOM + bentgpp1, data = bent_gpp)
)
sem.fit(exef_pSEM_randomList, bent_gpp)
`

**Comment by frva-umea** [comment] 2016-06-20 11:47
Thanks! 
It works!

**Closed** 2016-07-08 15:36 UTC
